[package]
name = "secure-common"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.79"

[dependencies.pqcrypto]
version = "0.17.0"
default-features = false
features = ["pqcrypto-kyber", "pqcrypto-sphincsplus"]
